### ISSUE TITLE
500 Internal Server Error when trying to add integration.

### ISSUE THREAD

**Issue by iTwenty** [Kir4Kun/ha-miraie-ac#3]
Steps taken
- Clone this repo
- Copy miraie folder to HA's config/custom_components/ folder
- Restart HA
- Try to add MirAIe Integration

The error I am getting is "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble".

I am new to the Home Assistant, so don't have much context on how to go about resolving this. Let me know if you need more information.

**Comment by iTwenty** [comment]
I looked into the full error logs. This is what I see in the logs -

```
[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
2023-03-11 20:26:43.811 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package aiohttp==3.8.1: ERROR: Cannot install aiohttp==3.8.1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Followed by

```
homeassistant.requirements.RequirementsNotFound: Requirements for miraie not found: ['aiohttp==3.8.1'].
```

It looks like a version conflict issue for aiohttp package. I will explore this a bit more.

**Comment by Kir4Kun** [comment]
@iTwenty I am aware of this issue. Panasonic changed its API, I will update it as soon I am free.

**Comment by Kir4Kun** [comment]
Issue solved.

**Comment by iTwenty** [comment]
Thanks @Kir4Kun. I tried it out and it works!

**Comment by kbipinkumar** [comment]
getting the same error as on 03-03-2024, maybe panasonic made some changes on their end?
![image](https://github.com/rkzofficial/ha-miraie-ac/assets/10775428/cd8e338c-8bf9-41f7-9f7a-0dc2cf8bc4dc)

**Comment by kbipinkumar** [comment]
> @kbipinkumar You can try updating the version of aiohttp. Current version is 3.9.3.

3.9.3 didnt work. 

however, removing dependency  `aiohttp` altogether from `manifest.json` seems to have worked
